### PR TITLE
Expand list of example groups

### PR DESCRIPTION
**Pull request by isaacvetter**
Group membership could even be based upon patients' age, sex or a particular condition such as PTSD or Chronic Opioid use or even a recent inpatient discharge.

### CODE REVIEW

**Comment by kbweaver** [comment]
The other example I can think of is using Group membership to represent populations of patients for quality reporting. For example, the [MeasureReport](https://www.hl7.org/fhir/measurereport.html) resource uses Lists of Patient resources to represent measure populations (numerator, denominator) and stratifications of those populations. Being able to export all data for a measure population sounds like it would be valuable to anyone who wants to run analytics against those populations.

**Comment by jmandel** [comment]
@isaacvetter to incorporate the measure-based suggestion into this PR

**Comment by isaacvetter** [comment]
@kbweaver, your suggestion is a bit complicated because of the two different ways that a MeasureReport and bulk data define a collection of patients. It sounds like we [might be able to unify](https://chat.fhir.org/#narrow/stream/4-implementers/subject/Group.20vs.20List.2E.20Should.20a.20Group.20be.20able.20to.20point.20to.20a.20List.3F) [these two mechanisms](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=17355), so I went ahead and added a phrase to this PR to suggest that it's possible.

**Comment by isaacvetter** [comment]
Hey @kbweaver , everybody,

Just FYI - the [gforge issue](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=17355)'s resolution will be to update the Measure and MeasureReport resources to support Group!

**Pull request merged**
