### PR TITLE
Revert "Add `kty` as required authentication JWT header"

### PR DESCRIPTION
**Pull request by jmandel**
Reverts smart-on-fhir/fhir-bulk-data-docs#83

### CODE REVIEW

**Comment by jmandel** [comment]
@dennispatterson thanks for your careful read -- this PR reverts and corrects #83 

@vlad-ignatov please take a look

I will merge after someone reviews :-)

**Review by dennispatterson — APPROVED** [review]

**Comment by vlad-ignatov** [comment]
I understand now that the `alg` header is required but the question is how will the `kty` be sent to the backend. The problem is in this sentence: 

Filter the potential keys to retain only those where the `kty` and `kid` match the values supplied in the client's JWK header.

It almost sounds like I have to compare `jwk.kty` with itself! Can you clarify that?

**Comment by dennispatterson** [comment]
I don't think the kty is expected to be in the jwt and I don't think it's a matter of comparing given values for kty. 
 Rather, given the kty values listed [here](https://tools.ietf.org/html/rfc7518#section-6.1) and algorithms [here](https://tools.ietf.org/html/rfc7518#section-7.1.2), I think it's intended to be understood that if the algorithm is RS___, the kty is RSA, whereas if the algorithm is ES___, the kty is EC.

**Comment by vlad-ignatov** [comment]
So then: 
1. I filter keys **only** by `kid`
2. Validate the filtered keys using `kty` and `alg` - seems useless to me because any invalid key should fail to verify anyway.

@jmandel What do you think?

**Comment by lcmaas** [comment]
I think there is some confusion in this thread because one key type (expressed by `kty`) can support multiple algorithms (expressed by `alg`), e.g. RSA key supports RS256, RS384, PS256, etc.

a `kty` value is required for each JWK entry in a key set. `alg` is optional in a JWK entry, e.g. if you want to signal that signing operations for that key are restricted to only certain hash or padding algorithms, e.g. this RSA key should be used only for RS256 and not PS256. Unless the signer has lots of keys, this this probably not relevant to this use case since the signing party is the one picking the algorithm, not the validating party.

`alg` is required in a signed JWT so you know which algorithm was actually used to make the signature and, thus, how to validate the signature. The required key type is implied by the algorithm, e.g. RS384 or PS256 means you need an RSA key.  `kty` should not be part of a JWT (unless for some reason a JWK is included as a component of the JWT). 

`kid` is optional in both JWK entries and JWTs. Be aware that `kid` values are not guaranteed to be unique (see [here](https://tools.ietf.org/html/rfc7517#section-4.5)). When present in a JWT, it is a "hint" to help you filter the keys in a JWKS, and can be helpful in key rollover situations to limit the number of keys that need to be tried to validate a signature.

**Comment by jmandel** [comment]
I updated the PR here to address the confusion about what "match" means for kty -- but I'd also be okay just removing this bit of text and saying "match on kid" alone, since there shouldn't be multiple different-typed JWKs in a given JWKS that share a kid.

**Review by vlad-ignatov — APPROVED** [review]
That looks good to me. In reality, I will only have to filter by `kid`. The `kty` vs `alg` comparison feels a little out of scope (because the verification should fail if these are wrong), but can be left as instructions for those who do low-level implementations and don't have a library that handles such validation.

**Review by dennispatterson — APPROVED** [review]

**Pull request merged**
