### PR TITLE
Clarify matching kty (not alg) and kid, when validating signatures

### PR DESCRIPTION
**Pull request by jmandel**

### CODE REVIEW

**Comment by daliboz** [comment]
Add a reference to https://tools.ietf.org/html/rfc7517 ? It does have a lot of rules around throwing away kty values you don't recognize, how to treat duplicates, etc?

**Comment by jmandel** [comment]
Just realized: We have a reference to https://tools.ietf.org/html/rfc7517 already when we introduce JWKS.

**Comment by vlad-ignatov** [comment]
Perhaps we should also update the **Authentication JWT Header Values** table? Now it says:


alg | required | The algorithm used for signing the authentication JWT (e.g., `RS384`, `EC384`).
-- | -- | --

but it should be:

kty | required | The type of key used for signing the authentication JWT (e.g., `RSA`, `EC`).
-- | -- | --

**Comment by jmandel** [comment]
Oh, I'd say so -- good catch! Since we already merged this pull request, would you be willing to open another?

**Comment by jmandel** [comment]
Oh, I'd say so -- good catch! Since we already merged this pull request, would you be willing to open another?

**Comment by vlad-ignatov** [comment]
OK, but do you think we should keep the `alg` as optional?

**Pull request merged**
