### PR TITLE
Specify OperationOutcomes in error conditions

### PR DESCRIPTION
**Pull request by jmandel**
Given FHIR-I discussion at https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=14495 I want to make sure we keep this in sync with the decision on today's call. Requiring an OperationOutcome in the error condition seems like a non-controvertial, useful step for interop.

@gotdan  @isaacvetter @daliboz thoughts?

### CODE REVIEW

**Comment by daliboz** [comment]
Is there anything specific we want to say about what should be in the OperationOutcome?

Edit: I assume other error sections should probably also require the OperationOutcome? For example, the status request and delete request. May want to discuss the file request error scenario - that could present challenges for some architectures, so I could see it being less desirable as a requirement.

**Comment by jmandel** [comment]
I'd be comfortable just saying it needs to be a valid Operation Outcome, until we get more experience with it. Agreed we may want to say this for all of the synchronous calls, in addition to the kick-off.

**Review by gotdan — DISMISSED** [review]
Added your new language to a few more places and specified JSON - does this look right?

**Comment by jmandel** [comment]
Looks good to me!

**Pull request merged**
