### PR TITLE
Clarify what `transactionTime` should be in the status response

### PR DESCRIPTION
**Pull request by vlad-ignatov**
Be explicit about this because one could think its the transaction start time (in which case the next sentence would be very difficult to implement)

### CODE REVIEW

**Comment by jmandel** [comment]
Hmm, I wonder if we're getting the meaning right here. If I'm trying to be explicit, I'd say the most important requirement of`transactionTime` is as follows (I think). Consider the following scenario:

1. Client performs bulk export and sees `transactionTime` of "x"
2. Time passes
3. Client performs bulk export with `_since=x`

In this case, every resource on the server should be present in *either* the export from (1) or the export from (2), but not both. Meaning that the transactionTime represents a lastUpdated timestamp before which all data have been considered for export, and after which no data have been considered for export.

First off, does this make sense? Second, do you think it's consistent with what the spec says, and that changing "run" to "completed" helps make this clear?

**Comment by vlad-ignatov** [comment]
My thinking initially was also that `transactionTime` can be used to build the subsequent export requests and therefore, it should equal the last point in time that we have already exported (further exports start from there).

Upon further consideration I've made the following conclusions:
1. The export is a long-running process. By the time the last `resourceType` is exported, the first one might already be out of date. That could happen if we export resources modified between `_since` and `now`, where `now` is in fact different for each resource type. 
2. The spec makes it look simpler than it is - just export everything since the given timestamp. In reality, the implementors must save the export start time in a variable (lets call it `before`) and use that as the latest possible `lastUpdated` instant. This way, all the exported resources will be in the same time range, regardless of when a resourceType have actually been processed. In this case the `before` variable is what we can return as `transactionTime` and the clients can safely use it to check for updates.
3. If we had an upper-bound param like `_before`, the variable described above would not be needed. I am even tempted to go further and support `_before` as optional param that defaults to `now` which would still be compatible with the spec. However, since adding parameters is not desirable at this point, I guess @2 is the way to go.

All that being said, I no longer thing that `complete` is better than `run`, but I do think it would be nice to describe the `transactionTime` better, and try to avoid the confusion caused by the lack of `_before` parameter. Even the name `transactionTime` is confusing. In fact, `started` seems to be the correct word here.

**Comment by jmandel** [comment]
Thanks for the assessment -- this is a careful and important analysis. Re conclusion (2), I agree this sounds like the right idea. One additional nuance is that at the time an export began, a busy server may have some db transactions (say, from POST / with a transaction type bundle) that are still in process and that may not have landed in the database yet. So the right behaviour for server is probably to take something like the maximum allowed transaction duration and subtract it from the current time to create the transactionTime value you describe in (2).

**Comment by jmandel** [comment]
@vlad-ignatov I'm inclined to write something like:

>   - ```transactionTime``` - a FHIR instant type that indicates the server's time when the query is run. The response SHOULD NOT include any resources modified after this instant, and SHALL include any matching resources modified up to (and including) this instant. Note: to properly meet these constraints, a FHIR Server might need to build a short delay into the export process (long enough for any pending transactions to resolve in its database).

Thoughts?

**Comment by vlad-ignatov** [comment]
Or maybe something even simpler like:

transactionTime - a FHIR instant type that indicates the server's time when the query is run. The response SHOULD NOT include any resources modified after this instant, and SHALL include any matching resources modified up to (and including) this instant. Note: to properly meet these constraints, a FHIR Server might need to wait for any pending transactions to resolve in its database, before starting the export process.

**Comment by jmandel** [comment]
OK, done. I updated and fixed the git conflict. @gotdan do you want to review and merge if you're happy?

**Comment by vlad-ignatov** [comment]
Yes, it looks good to me. Thanks!

**Pull request merged**
